name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: git.determi.io/determi-io/prebuilt-dependencies:dev-2023-10-27
    steps:
      - name: Build with nix
        run: nix build .


